[global]
showWarningOnDirectExecution = false
[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[ui]
hideTopBar = true

[theme]
base = "light"
primaryColor = "#00c292"
backgroundColor = "#f4f7f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#1f2937"
font = "sans serif"
